export const categories = [
  {
    id: 'personalInfo',
    label: 'Personal Info',
    fields: [
      'name',
      'email',
      'phone',
      'address',
      'linkedIn_Link',
      'gitHub_Link',
      'portfolio_Link',
    ],
    required: ['name', 'email', 'phone', 'address'],
  },
  {
    id: 'education',
    label: 'Education',
    fields: [
      'college_Name',
      'location',
      'degree',
      'field',
      'gpa_Score',
      'start_Date',
      'end_Date',
      'current',
    ],
    required: [
      'college_Name',
      'location',
      'degree',
      'field',
      'start_Date',
      'end_Date',
    ],
  },
  {
    id: 'experience',
    label: 'Experience',
    fields: [
      'company_Name',
      'role',
      'start_Date',
      'end_Date',
      'current',
      'location',
      'description',
    ],
    required: [
      'company_Name',
      'role',
      'start_Date',
      'end_Date',
      'location',
      'description',
    ],
  },
  {
    id: 'projects',
    label: 'Projects',
    fields: ['title', 'project_Link', 'description'],
    required: ['title', 'description'],
  },
  {
    id: 'skills',
    label: 'Technical Skills',
    fields: [],
    required: [],
  },
  {
    id: 'additional',
    label: 'Additional',
    fields: [
      'title',
      'link',
      'start_Date',
      'end_Date',
      'current',
      'description',
    ],
    required: [],
  },
];
